### Submission 3: Parse remote content during change of Mind
#### Insert into table ChangeofMindTheta

In [1]:
%reload_ext autoreload
%autoreload 2

In [2]:
import numpy as np
import pandas as pd
import pickle
import xarray as xr
import matplotlib.pyplot as plt
from scipy.stats import ranksums
import seaborn as sns
import copy

In [3]:
from spyglass.shijiegu.Analysis_SGU import get_linearization_map

from spyglass.shijiegu.Analysis_SGU import TrialChoice, DecodeIngredients, DecodeResults2D, ChangeofMind, ChangeofMindRemoteTheta, DecodeResultsLinear, ChangeofMindTriggeredDecode
from spyglass.shijiegu.decodeHelpers import runSessionNames
from spyglass.utils.nwb_helper_fn import get_nwb_copy_filename
from spyglass.decoding.v0.visualization import make_single_environment_movie
from spyglass.shijiegu.changeOfMind_triggered_position import load_triggered_position_decode_day
from spyglass.shijiegu.changeOfMind_triggered import select_subset_helper_position
from spyglass.shijiegu.changeOfMind_remote import find_posterior_sum_segment, find_remote_theta_animal_new
from spyglass.shijiegu.changeOfMind_remote_interval import find_remote_theta_animal, parse_remote_master, load_remote_animal

[2026-04-03 10:27:58,753][INFO]: DataJoint 0.14.4 connected to shijiegu-alt@lmf-db.cin.ucsf.edu:3306
[10:28:12][WARNING] Spyglass: Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
WARNING:spyglass:Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
[10:28:12][WARNING] Spyglass: Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
WARNING:spyglass:Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
[10:28:12][WARNING] Spyglass: Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
WARNING:spyglass:Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
[10:28:13][WARNING] Spyglass: Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
WARNING:spyglass:Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
[10:28:13][WARNING] Spyglass: Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
WARNING:spyglass:Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
[10:28:13][WARNING] Spyglass: Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.
WARNING:spyglass:Deprecation: this class has been moved out of spyglass.common.common_position
	TrackGraph -> spyglass.linearization.v0.main.TrackGraph
Please use the new location.

In [4]:
ChangeofMindTriggeredDecode() & {"nwb_file_name": "julio20230801_.nwb"}#"klein20231108_.nwb", "parameter":"params_both_control_max_segment_run_time_2_state"}#"julio20230811_.nwb"}#"parameter":"params_both_max_run_time_2_state"}#"parameter":"params_both_max_segment_run_time_2_state"}

*nwb_file_name *epoch    *proportion    *parameter     analysis_file_ parameter_
+------------+ +-------+ +------------+ +------------+ +------------+ +--------+
julio20230801_ 2         0.1            params_both_co julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_both_co julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_both_ma julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_both_ma julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_post_al julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_post_co julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_post_ru julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_pre_all julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_pre_con julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_pre_con julio20230801_ =BLOB=
julio20230801_ 2         0.1            params_pre_run julio20230801_ =BLOB=
julio20230801_ 4         0.1            params_both_co julio20230801_ =BLOB=
   ...
 (Total: 63)

In [13]:
params = {"use_1d": True,
          "use_home": False,
          "use_center": False,
          "use_outer": True,
          "proportion":0.1,
          "parameter_name": "params_both_max_all_maze_2_state"}

In [14]:
list_of_days_animals = {}
success_animal = {}

animal = "eliot"
list_of_days_animals[animal] = ['20221018','20221019','20221020','20221021','20221022','20221023','20221024','20221025','20221026']

animal = "molly"
list_of_days_animals[animal]  = ['20220416','20220417','20220418','20220419','20220420']

animal = 'lewis'
list_of_days_animals[animal] = ['20240105','20240106','20240107','20240108','20240109',
                 '20240110']

animal = 'julio'
list_of_days_animals[animal] = ['20230731','20230801','20230802','20230803','20230804',
                 '20230805','20230806','20230807','20230808','20230809','20230810','20230811']

animal = 'klein'
list_of_days_animals[animal]  = ['20231101','20231102','20231103','20231104','20231105',
                 '20231106','20231107','20231108']

### 2. debug start

In [20]:
log_df = pd.DataFrame((ChangeofMindRemoteTheta() & {"nwb_file_name": "molly20220418_.nwb","epoch":10,
                                                    "parameter":"params_both_max_all_maze_2_state"}).fetch1("pandas"))
log_df_com = log_df[log_df.has_remote_interval]
log_df_com

,timestamp_H,Home,timestamp_O,OuterWellIndex,rewardNum,change_of_mind,has_remote_interval,remote_interval,remote_content,change_of_mind_num,...,proportion_arm3,proportion_arm4,CoMNum_by_time,CoMNum_by_arm,CoM_arm,current,future_H,future_O,past,past_reward
28,1.650325e+09,1.0,1.650325e+09,4.0,1.0,True,True,"[[1650325175.3036144, 1650325175.3856144], [16...","[0, 0, 0, 0]","[0, 0, 0, 0]",...,0.584492,0.000000,1,1,"[[3, 4, -9223372036854775808]]",4.0,4.0,1.0,2.0,2.0
34,1.650325e+09,1.0,1.650325e+09,4.0,1.0,True,True,"[[1650325328.8835862, 1650325328.947586], [165...","[0, 0, 0, 0, 0]","[0, 0, 0, 0, 0]",...,0.000000,0.000000,2,2,"[[2, 1, 4]]",4.0,4.0,3.0,1.0,1.0
39,1.650325e+09,1.0,1.650325e+09,3.0,1.0,True,True,"[[1650325473.2475595, 1650325473.2775595]]",[1],[0],...,0.000000,0.360574,1,1,"[[4, 3, -9223372036854775808]]",3.0,3.0,1.0,2.0,2.0

In [21]:
log_df = pd.DataFrame((ChangeofMindRemoteTheta() & {"nwb_file_name": "molly20220418_.nwb","epoch":10,
                                                    "parameter":"params_both_max_run_time_2_state"}).fetch1("pandas"))
log_df_com = log_df[log_df.has_remote_interval]
log_df_com

,timestamp_H,Home,timestamp_O,OuterWellIndex,rewardNum,change_of_mind,has_remote_interval,remote_interval,remote_content,change_of_mind_num,...,proportion_arm3,proportion_arm4,CoMNum_by_time,CoMNum_by_arm,CoM_arm,current,future_H,future_O,past,past_reward
17,1.650325e+09,1.0,1.650325e+09,2.0,2.0,True,True,"[[1650324943.373657, 1650324943.399657], [1650...","[0, 0]","[0, 0]",...,0.000000,0.626893,2,2,"[[4, 1, 2, -9223372036854775808]]",2.0,2.0,4.0,1.0,4.0
28,1.650325e+09,1.0,1.650325e+09,4.0,1.0,True,True,"[[1650325175.3416142, 1650325175.3916142]]",[4],[0],...,0.584492,0.000000,1,1,"[[3, 4, -9223372036854775808]]",4.0,4.0,1.0,2.0,2.0
39,1.650325e+09,1.0,1.650325e+09,3.0,1.0,True,True,"[[1650325473.2475595, 1650325473.2775595]]",[1],[0],...,0.000000,0.360574,1,1,"[[4, 3, -9223372036854775808]]",3.0,3.0,1.0,2.0,2.0

### 2. debug end

In [15]:
params = {"use_1d": True,
          "use_home": False,
          "use_center": False,
          "use_outer": True,
          "proportion":0.1,
          "parameter_name": "params_both_max_all_maze_2_state"}#"params_both_max_run_time_2_state"} #"params_both_max_all_maze_2_state", "params_both_max_run_time_2_state"

success_animal = {}
for animal in ["lewis","eliot","molly","klein","julio"]:#list_of_days_animals.keys():
    days = list_of_days_animals[animal]
    success = parse_remote_master(animal,
                      days,
                      params,
                      minimum_duration = 0.02,
                      min_sum_posterior = 0.2,
                      fill_spyglass = True)

    success_animal[animal] = success

[2026-01-25 20:40:33,503][WARNING]: Skipped checksum for file with hash: b13385bc-86f6-f0fa-922b-9e4a5ccea5fb, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_CTI07FVT1J.nwb
WARNING:datajoint:Skipped checksum for file with hash: b13385bc-86f6-f0fa-922b-9e4a5ccea5fb, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_CTI07FVT1J.nwb

lewis20240105_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240105_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [42, 42, 42]
Found remote theta in trial  [46]
Found remote theta in trial  [50, 50, 50, 50, 50, 50]
Found remote theta in trial  [62]
Found remote theta in trial  [65]
Found remote theta in trial  [66]
Found remote theta in trial  [70, 70, 70, 70, 70, 70, 70, 70]
Found remote theta in trial  [71, 71]
Found remote theta in trial  [88]

[2026-01-25 20:40:50,669][WARNING]: Skipped checksum for file with hash: b3b4c94a-5c8c-19c9-fd43-efe78342ac39, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_9YD57CSAZY.nwb
WARNING:datajoint:Skipped checksum for file with hash: b3b4c94a-5c8c-19c9-fd43-efe78342ac39, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_9YD57CSAZY.nwb

Found remote theta in trial  [98, 98, 98, 98, 98, 98, 98]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240105_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [5]
Found remote theta in trial  [9, 9]
Found remote theta in trial  [16]
Found remote theta in trial  [19]
Found remote theta in trial  [22, 22, 22]
Found remote theta in trial  [30, 30, 30]
Found remote theta in trial  [43]
Found remote theta in trial  [77, 77]

[2026-01-25 20:41:04,504][WARNING]: Skipped checksum for file with hash: 40e08994-024e-5e63-f8ff-f2b513dba795, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_NLFK1MPAM4.nwb
WARNING:datajoint:Skipped checksum for file with hash: 40e08994-024e-5e63-f8ff-f2b513dba795, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_NLFK1MPAM4.nwb

Found remote theta in trial  [81]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240105_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [12, 12]
Found remote theta in trial  [16]
Found remote theta in trial  [29, 29]
Found remote theta in trial  [29]
Found remote theta in trial  [51]

[2026-01-25 20:41:19,186][WARNING]: Skipped checksum for file with hash: 63a37cd2-3d55-e6c0-644a-d29c7efd9254, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_KMDIJI2ZFI.nwb
WARNING:datajoint:Skipped checksum for file with hash: 63a37cd2-3d55-e6c0-644a-d29c7efd9254, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_KMDIJI2ZFI.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240105_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [16]
Found remote theta in trial  [20]

[2026-01-25 20:41:32,569][WARNING]: Skipped checksum for file with hash: 9ae7b83d-1cee-e30f-8f67-c095800cea40, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_0YSWV5ZHPH.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9ae7b83d-1cee-e30f-8f67-c095800cea40, and path: /stelmo/nwb/analysis/lewis20240105/lewis20240105_0YSWV5ZHPH.nwb

Found remote theta in trial  [27, 27]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240105_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:41:42,313][WARNING]: Skipped checksum for file with hash: 7c29c024-7097-40c4-8900-9af217b07cc9, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_2FVO3R4G9J.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7c29c024-7097-40c4-8900-9af217b07cc9, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_2FVO3R4G9J.nwb

lewis20240106_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240106_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [15]
Found remote theta in trial  [30]
Found remote theta in trial  [39, 39]
Found remote theta in trial  [43]
Found remote theta in trial  [69]

[2026-01-25 20:41:55,068][WARNING]: Skipped checksum for file with hash: 9a75de87-3ed8-8c73-b276-f3302c534fe3, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_TLF66WDFF7.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9a75de87-3ed8-8c73-b276-f3302c534fe3, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_TLF66WDFF7.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240106_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [16, 16, 16, 16]
Found remote theta in trial  [34, 34]
Found remote theta in trial  [47]
Found remote theta in trial  [67, 67, 67]
Found remote theta in trial  [74, 74, 74]
Found remote theta in trial  [75]

[2026-01-25 20:42:08,835][WARNING]: Skipped checksum for file with hash: feb4d9b2-3bcf-1c2d-13a6-b366f7f76ee2, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_GYVYUZA7N4.nwb
WARNING:datajoint:Skipped checksum for file with hash: feb4d9b2-3bcf-1c2d-13a6-b366f7f76ee2, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_GYVYUZA7N4.nwb

Found remote theta in trial  [83, 83]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240106_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [25, 25]

[2026-01-25 20:42:20,952][WARNING]: Skipped checksum for file with hash: df109b01-abb4-d513-8c91-09affdff3cc2, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_8ESNV4ZOZG.nwb
WARNING:datajoint:Skipped checksum for file with hash: df109b01-abb4-d513-8c91-09affdff3cc2, and path: /stelmo/nwb/analysis/lewis20240106/lewis20240106_8ESNV4ZOZG.nwb

Found remote theta in trial  [44]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240106_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [13, 13, 13]
Found remote theta in trial  [14, 14]

[2026-01-25 20:42:33,487][WARNING]: Skipped checksum for file with hash: 85e2fa60-a51f-1a6a-869b-1262e7e2b44f, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_5EBN8YYO5V.nwb
WARNING:datajoint:Skipped checksum for file with hash: 85e2fa60-a51f-1a6a-869b-1262e7e2b44f, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_5EBN8YYO5V.nwb

Found remote theta in trial  [18]
lewis20240107_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240107_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [36]
Found remote theta in trial  [46]
Found remote theta in trial  [47]
Found remote theta in trial  [47, 47]

[2026-01-25 20:42:46,355][WARNING]: Skipped checksum for file with hash: c2f46600-2386-0f0a-888f-cb0515308c9a, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_0PFFQMKLLN.nwb
WARNING:datajoint:Skipped checksum for file with hash: c2f46600-2386-0f0a-888f-cb0515308c9a, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_0PFFQMKLLN.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240107_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:42:58,817][WARNING]: Skipped checksum for file with hash: 396e0f44-a83f-2483-231f-03cd0d61623a, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_9X9GJ5ERIH.nwb
WARNING:datajoint:Skipped checksum for file with hash: 396e0f44-a83f-2483-231f-03cd0d61623a, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_9X9GJ5ERIH.nwb

Found remote theta in trial  [27]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240107_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [23, 23, 23, 23]
Found remote theta in trial  [37]

[2026-01-25 20:43:11,854][WARNING]: Skipped checksum for file with hash: 6ae639cc-0f1d-4adf-7dc6-722c748e6e16, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_9XDZHQ55HP.nwb
WARNING:datajoint:Skipped checksum for file with hash: 6ae639cc-0f1d-4adf-7dc6-722c748e6e16, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_9XDZHQ55HP.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240107_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10]
Found remote theta in trial  [17]
Found remote theta in trial  [41]
Found remote theta in trial  [49]

[2026-01-25 20:43:24,336][WARNING]: Skipped checksum for file with hash: d9bc93ad-b76e-ea63-a01d-4658ec051d4a, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_3Z8AZ6B0C6.nwb
WARNING:datajoint:Skipped checksum for file with hash: d9bc93ad-b76e-ea63-a01d-4658ec051d4a, and path: /stelmo/nwb/analysis/lewis20240107/lewis20240107_3Z8AZ6B0C6.nwb

Found remote theta in trial  [50, 50, 50]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240107_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10, 10, 10]

[2026-01-25 20:43:35,963][WARNING]: Skipped checksum for file with hash: 648a4b0f-d3e1-a87e-c183-63840e2a2846, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_1DGY0IOSQK.nwb
WARNING:datajoint:Skipped checksum for file with hash: 648a4b0f-d3e1-a87e-c183-63840e2a2846, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_1DGY0IOSQK.nwb

Found remote theta in trial  [38, 38]
lewis20240108_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240108_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [5]
Found remote theta in trial  [44, 44, 44]
Found remote theta in trial  [48, 48, 48, 48, 48, 48, 48]
Found remote theta in trial  [52, 52]
Found remote theta in trial  [60, 60, 60, 60]
Found remote theta in trial  [60, 60, 60, 60, 60, 60, 60, 60, 60, 60]
Found remote theta in trial  [65, 65, 65]
Found remote theta in trial  [67]
Found remote theta in trial  [67, 67, 67, 67, 67, 67]

[2026-01-25 20:43:50,021][WARNING]: Skipped checksum for file with hash: 8f860978-4f47-a4a2-5268-a191cd4c4d86, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_VXLFNTEFOB.nwb
WARNING:datajoint:Skipped checksum for file with hash: 8f860978-4f47-a4a2-5268-a191cd4c4d86, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_VXLFNTEFOB.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240108_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10, 10]
Found remote theta in trial  [15, 15]
Found remote theta in trial  [16]
Found remote theta in trial  [18, 18, 18]
Found remote theta in trial  [18, 18]
Found remote theta in trial  [21]
Found remote theta in trial  [32]
Found remote theta in trial  [51]
Found remote theta in trial  [53, 53, 53, 53, 53]
Found remote theta in trial  [54]
Found remote theta in trial  [58, 58, 58, 58]
Found remote theta in trial  [61, 61]
Found remote theta in trial  [61]
Found remote theta in trial  [62, 62, 62]
Found remote theta in trial  [69, 69]

[2026-01-25 20:44:04,112][WARNING]: Skipped checksum for file with hash: 1495b7ce-afd8-6b20-fa10-61311a0ae6ac, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_PU4YV1FEXZ.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1495b7ce-afd8-6b20-fa10-61311a0ae6ac, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_PU4YV1FEXZ.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240108_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [23, 23, 23]
Found remote theta in trial  [39]

[2026-01-25 20:44:16,774][WARNING]: Skipped checksum for file with hash: 5f3d216d-8e74-437d-55fc-5455935e01d4, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_2ME6MF58W2.nwb
WARNING:datajoint:Skipped checksum for file with hash: 5f3d216d-8e74-437d-55fc-5455935e01d4, and path: /stelmo/nwb/analysis/lewis20240108/lewis20240108_2ME6MF58W2.nwb

Found remote theta in trial  [43, 43, 43, 43]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240108_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [19]
Found remote theta in trial  [23, 23, 23]
Found remote theta in trial  [32, 32, 32, 32]
Found remote theta in trial  [35, 35, 35, 35, 35]
Found remote theta in trial  [44, 44, 44]

[2026-01-25 20:44:30,015][WARNING]: Skipped checksum for file with hash: 2cdd5980-eb4e-f719-1888-61acd592c279, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_45DCTFBBB3.nwb
WARNING:datajoint:Skipped checksum for file with hash: 2cdd5980-eb4e-f719-1888-61acd592c279, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_45DCTFBBB3.nwb

Found remote theta in trial  [51, 51, 51, 51, 51, 51, 51]
Found remote theta in trial  [53, 53]
lewis20240109_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240109_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [18]

[2026-01-25 20:44:43,937][WARNING]: Skipped checksum for file with hash: c3a51c7a-2652-50c7-06e2-e468a3a40fc3, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_A2D0XCWD25.nwb
WARNING:datajoint:Skipped checksum for file with hash: c3a51c7a-2652-50c7-06e2-e468a3a40fc3, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_A2D0XCWD25.nwb

Found remote theta in trial  [81, 81, 81]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240109_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [13, 13, 13]
Found remote theta in trial  [39, 39, 39]
Found remote theta in trial  [43, 43]
Found remote theta in trial  [44, 44, 44, 44, 44, 44, 44]
Found remote theta in trial  [45, 45]
Found remote theta in trial  [53, 53, 53]
Found remote theta in trial  [53]
Found remote theta in trial  [63, 63, 63, 63, 63, 63, 63]
Found remote theta in trial  [63, 63, 63, 63, 63]
Found remote theta in trial  [66]
Found remote theta in trial  [76, 76]

[2026-01-25 20:44:59,013][WARNING]: Skipped checksum for file with hash: e42448a7-4432-2d14-192c-95c7c7114394, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_PKXGIG5QY8.nwb
WARNING:datajoint:Skipped checksum for file with hash: e42448a7-4432-2d14-192c-95c7c7114394, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_PKXGIG5QY8.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240109_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [9, 9]
Found remote theta in trial  [14, 14]
Found remote theta in trial  [14]
Found remote theta in trial  [23, 23, 23, 23, 23, 23]
Found remote theta in trial  [24, 24]
Found remote theta in trial  [28, 28, 28, 28, 28]
Found remote theta in trial  [33]

[2026-01-25 20:45:13,215][WARNING]: Skipped checksum for file with hash: 9eccad9b-f2f5-e4af-2094-5dc0f492845a, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_XHF5C3JLX4.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9eccad9b-f2f5-e4af-2094-5dc0f492845a, and path: /stelmo/nwb/analysis/lewis20240109/lewis20240109_XHF5C3JLX4.nwb

Found remote theta in trial  [64, 64]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240109_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [16]

[2026-01-25 20:45:25,130][WARNING]: Skipped checksum for file with hash: 62c2e3c3-dd9a-0052-6e11-40cd22935401, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_WLSPL5TWBQ.nwb
WARNING:datajoint:Skipped checksum for file with hash: 62c2e3c3-dd9a-0052-6e11-40cd22935401, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_WLSPL5TWBQ.nwb

Found remote theta in trial  [20, 20, 20, 20, 20, 20]
lewis20240110_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240110_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [11, 11, 11]
Found remote theta in trial  [15, 15]
Found remote theta in trial  [16]
Found remote theta in trial  [19, 19]
Found remote theta in trial  [25, 25, 25]
Found remote theta in trial  [25]
Found remote theta in trial  [25, 25, 25, 25, 25, 25]
Found remote theta in trial  [48, 48]
Found remote theta in trial  [65, 65, 65, 65]
Found remote theta in trial  [66, 66, 66, 66]

[2026-01-25 20:45:38,892][WARNING]: Skipped checksum for file with hash: 8d9facfb-6544-1d6c-e92b-404a3f1b4bd4, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_WTBVR8NV6U.nwb
WARNING:datajoint:Skipped checksum for file with hash: 8d9facfb-6544-1d6c-e92b-404a3f1b4bd4, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_WTBVR8NV6U.nwb

Found remote theta in trial  [81, 81]
Found remote theta in trial  [81, 81, 81]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240110_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [12, 12]
Found remote theta in trial  [15, 15]
Found remote theta in trial  [17, 17, 17, 17, 17, 17, 17, 17, 17, 17, 17]
Found remote theta in trial  [22, 22]
Found remote theta in trial  [24, 24]
Found remote theta in trial  [29]
Found remote theta in trial  [45]
Found remote theta in trial  [60]
Found remote theta in trial  [65, 65, 65, 65]

[2026-01-25 20:45:53,518][WARNING]: Skipped checksum for file with hash: 23d814ef-6573-f1c5-85b6-8577be6ae9ac, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_P3MHGF3FTP.nwb
WARNING:datajoint:Skipped checksum for file with hash: 23d814ef-6573-f1c5-85b6-8577be6ae9ac, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_P3MHGF3FTP.nwb

Found remote theta in trial  [73, 73, 73, 73]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240110_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10, 10, 10]
Found remote theta in trial  [16]
Found remote theta in trial  [16, 16, 16]
Found remote theta in trial  [16, 16, 16, 16, 16, 16]
Found remote theta in trial  [35]
Found remote theta in trial  [45]
Found remote theta in trial  [51]

[2026-01-25 20:46:06,604][WARNING]: Skipped checksum for file with hash: 5d001e6d-52ae-ef36-ad04-6cbdb3806fb0, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_SGRZY9ZMA6.nwb
WARNING:datajoint:Skipped checksum for file with hash: 5d001e6d-52ae-ef36-ad04-6cbdb3806fb0, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_SGRZY9ZMA6.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240110_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:46:17,429][WARNING]: Skipped checksum for file with hash: a9929c8e-ffea-4ba5-9e80-31caa533c290, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_0OC4ILRBM3.nwb
WARNING:datajoint:Skipped checksum for file with hash: a9929c8e-ffea-4ba5-9e80-31caa533c290, and path: /stelmo/nwb/analysis/lewis20240110/lewis20240110_0OC4ILRBM3.nwb

Found remote theta in trial  [15]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
lewis20240110_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:46:28,238][WARNING]: Skipped checksum for file with hash: bb1969c5-cb8f-8540-857a-a637a6dd2372, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_4ISUY9PW38.nwb
WARNING:datajoint:Skipped checksum for file with hash: bb1969c5-cb8f-8540-857a-a637a6dd2372, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_4ISUY9PW38.nwb

Found remote theta in trial  [18, 18]
Found remote theta in trial  [35]
eliot20221018_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221018_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:46:37,154][WARNING]: Skipped checksum for file with hash: d0f077fa-be14-641c-b4d0-3b6eb8747f81, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_4S4IYRRH1J.nwb
WARNING:datajoint:Skipped checksum for file with hash: d0f077fa-be14-641c-b4d0-3b6eb8747f81, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_4S4IYRRH1J.nwb

No triggered decode found for  {'nwb_file_name': 'eliot20221018_.nwb', 'epoch': 4, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221018_ 5         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:46:45,390][WARNING]: Skipped checksum for file with hash: ae600b86-c9ac-ee06-28a4-8dddd50ecfc1, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_ET7U2NP6ZP.nwb
WARNING:datajoint:Skipped checksum for file with hash: ae600b86-c9ac-ee06-28a4-8dddd50ecfc1, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_ET7U2NP6ZP.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221018_ 7         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:46:53,697][WARNING]: Skipped checksum for file with hash: 42da0ac2-7470-2189-a4b3-97492d14c5af, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_7LKVQISEE8.nwb
WARNING:datajoint:Skipped checksum for file with hash: 42da0ac2-7470-2189-a4b3-97492d14c5af, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_7LKVQISEE8.nwb

Found remote theta in trial  [30, 30]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221018_ 9         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:47:01,292][WARNING]: Skipped checksum for file with hash: 9c492a35-bff9-7b7a-a681-5367f6ed6c92, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_IT83P0U61X.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9c492a35-bff9-7b7a-a681-5367f6ed6c92, and path: /stelmo/nwb/analysis/eliot20221018/eliot20221018_IT83P0U61X.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221018_ 11        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:47:09,951][WARNING]: Skipped checksum for file with hash: ac0b678f-0adb-bd68-52d4-530b60cc7b53, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_NXFL09ATWL.nwb
WARNING:datajoint:Skipped checksum for file with hash: ac0b678f-0adb-bd68-52d4-530b60cc7b53, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_NXFL09ATWL.nwb

eliot20221019_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221019_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10]
Found remote theta in trial  [52, 52, 52]
Found remote theta in trial  [57]
Found remote theta in trial  [57]

[2026-01-25 20:47:18,491][WARNING]: Skipped checksum for file with hash: 1d31f16a-870e-99af-358a-c6da9a7d42eb, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_MMQ8LKZTK5.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1d31f16a-870e-99af-358a-c6da9a7d42eb, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_MMQ8LKZTK5.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221019_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [16, 16]
Found remote theta in trial  [18]
Found remote theta in trial  [20, 20, 20]
Found remote theta in trial  [76, 76, 76, 76]
Found remote theta in trial  [76, 76]

[2026-01-25 20:47:28,426][WARNING]: Skipped checksum for file with hash: 16249820-dfc5-5b6c-12e9-839b961ec67a, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_OZGJ3UP795.nwb
WARNING:datajoint:Skipped checksum for file with hash: 16249820-dfc5-5b6c-12e9-839b961ec67a, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_OZGJ3UP795.nwb

Found remote theta in trial  [81]
Found remote theta in trial  [81, 81, 81]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221019_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [15]
Found remote theta in trial  [15, 15, 15, 15, 15, 15]
Found remote theta in trial  [44]

[2026-01-25 20:47:37,517][WARNING]: Skipped checksum for file with hash: 41505600-ca97-8b53-ffe2-3b62236298a5, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_9QH8445LQ5.nwb
WARNING:datajoint:Skipped checksum for file with hash: 41505600-ca97-8b53-ffe2-3b62236298a5, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_9QH8445LQ5.nwb

Found remote theta in trial  [73, 73, 73, 73]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221019_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [17, 17, 17]
Found remote theta in trial  [25, 25]
Found remote theta in trial  [25]
Found remote theta in trial  [33, 33, 33, 33, 33]

[2026-01-25 20:47:47,555][WARNING]: Skipped checksum for file with hash: f78b3946-871f-206a-f2d4-717e9a5fe0b7, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_5LHD6JGQO1.nwb
WARNING:datajoint:Skipped checksum for file with hash: f78b3946-871f-206a-f2d4-717e9a5fe0b7, and path: /stelmo/nwb/analysis/eliot20221019/eliot20221019_5LHD6JGQO1.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221019_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [26]
Found remote theta in trial  [28]
Found remote theta in trial  [32, 32]

[2026-01-25 20:47:56,049][WARNING]: Skipped checksum for file with hash: 1ea6a097-c88c-7133-dff4-6c6bd9ca001d, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_6X535072QF.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1ea6a097-c88c-7133-dff4-6c6bd9ca001d, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_6X535072QF.nwb

eliot20221020_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221020_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [24]

[2026-01-25 20:48:04,982][WARNING]: Skipped checksum for file with hash: 5b2217c0-81d9-66a3-9032-fc15689db4df, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_QGYWH23PIP.nwb
WARNING:datajoint:Skipped checksum for file with hash: 5b2217c0-81d9-66a3-9032-fc15689db4df, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_QGYWH23PIP.nwb

Found remote theta in trial  [52, 52]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221020_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [18, 18]

[2026-01-25 20:48:13,794][WARNING]: Skipped checksum for file with hash: 26eb07d9-c316-a5a1-0f41-64e6131ed5a3, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_0AFR6Y5483.nwb
WARNING:datajoint:Skipped checksum for file with hash: 26eb07d9-c316-a5a1-0f41-64e6131ed5a3, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_0AFR6Y5483.nwb

Found remote theta in trial  [53, 53, 53]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221020_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [44, 44, 44, 44, 44]

[2026-01-25 20:48:22,965][WARNING]: Skipped checksum for file with hash: e11524c5-0dda-2780-e8a0-50b29763b176, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_CA3S5LCBNW.nwb
WARNING:datajoint:Skipped checksum for file with hash: e11524c5-0dda-2780-e8a0-50b29763b176, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_CA3S5LCBNW.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221020_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:48:31,745][WARNING]: Skipped checksum for file with hash: 3411c25a-9644-1004-af24-db6905c9c782, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_71X52ULKHM.nwb
WARNING:datajoint:Skipped checksum for file with hash: 3411c25a-9644-1004-af24-db6905c9c782, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_71X52ULKHM.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221020_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:48:40,517][WARNING]: Skipped checksum for file with hash: e13e0cc0-2236-2d96-e458-a7c8e26d73ab, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_W3S0HCU24V.nwb
WARNING:datajoint:Skipped checksum for file with hash: e13e0cc0-2236-2d96-e458-a7c8e26d73ab, and path: /stelmo/nwb/analysis/eliot20221020/eliot20221020_W3S0HCU24V.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221020_ 12        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10]
Found remote theta in trial  [19]
Found remote theta in trial  [28, 28]
Found remote theta in trial  [44]
Found remote theta in trial  [53]

[2026-01-25 20:48:49,722][WARNING]: Skipped checksum for file with hash: 95c07b8a-ecb9-9acd-d3e1-5f67c0729f6f, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_8SRRL4RLY8.nwb
WARNING:datajoint:Skipped checksum for file with hash: 95c07b8a-ecb9-9acd-d3e1-5f67c0729f6f, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_8SRRL4RLY8.nwb

Found remote theta in trial  [60]
eliot20221021_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221021_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [55]
Found remote theta in trial  [55, 55, 55, 55, 55, 55]
Found remote theta in trial  [62, 62, 62, 62, 62]
Found remote theta in trial  [71, 71, 71, 71, 71]

[2026-01-25 20:48:59,587][WARNING]: Skipped checksum for file with hash: 87175bf1-20dd-6d56-91c3-b86bfeedc6af, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_2RCHKUL94G.nwb
WARNING:datajoint:Skipped checksum for file with hash: 87175bf1-20dd-6d56-91c3-b86bfeedc6af, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_2RCHKUL94G.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221021_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [29, 29, 29]
Found remote theta in trial  [29, 29, 29]
Found remote theta in trial  [38]
Found remote theta in trial  [68, 68, 68, 68]

[2026-01-25 20:49:08,998][WARNING]: Skipped checksum for file with hash: 7d7b67bd-7f95-f5a1-99f7-f4262e726a4b, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_7AY5211FMH.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7d7b67bd-7f95-f5a1-99f7-f4262e726a4b, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_7AY5211FMH.nwb

Found remote theta in trial  [78]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221021_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [11, 11, 11]

[2026-01-25 20:49:17,749][WARNING]: Skipped checksum for file with hash: c396b46e-0929-ae81-338f-7e6d23bd3abe, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_RTKZLRAROV.nwb
WARNING:datajoint:Skipped checksum for file with hash: c396b46e-0929-ae81-338f-7e6d23bd3abe, and path: /stelmo/nwb/analysis/eliot20221021/eliot20221021_RTKZLRAROV.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221021_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [60, 60, 60]
Found remote theta in trial  [76]

[2026-01-25 20:49:26,845][WARNING]: Skipped checksum for file with hash: 1e2d79bc-9796-0f5f-9212-632a85127d75, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_OLP9DGVEDW.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1e2d79bc-9796-0f5f-9212-632a85127d75, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_OLP9DGVEDW.nwb

Found remote theta in trial  [78, 78, 78, 78]
eliot20221022_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221022_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [8]
Found remote theta in trial  [16, 16, 16]

[2026-01-25 20:49:36,273][WARNING]: Skipped checksum for file with hash: e56d42ee-63aa-3829-7003-2b7053d3217a, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_DDI0EQVFNA.nwb
WARNING:datajoint:Skipped checksum for file with hash: e56d42ee-63aa-3829-7003-2b7053d3217a, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_DDI0EQVFNA.nwb

Found remote theta in trial  [41]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221022_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:49:44,826][WARNING]: Skipped checksum for file with hash: 861eb16f-1001-c06a-cd23-efd2b3a4e9d9, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_AKGMO8HPEY.nwb
WARNING:datajoint:Skipped checksum for file with hash: 861eb16f-1001-c06a-cd23-efd2b3a4e9d9, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_AKGMO8HPEY.nwb

Found remote theta in trial  [76]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221022_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:49:52,834][WARNING]: Skipped checksum for file with hash: f02e51af-c9e5-97cf-c1b6-c0d199204665, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_L97V36RRXU.nwb
WARNING:datajoint:Skipped checksum for file with hash: f02e51af-c9e5-97cf-c1b6-c0d199204665, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_L97V36RRXU.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221022_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:50:00,823][WARNING]: Skipped checksum for file with hash: afad33a9-bda1-2343-aaee-3a8e07eab293, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_A6ZIRB9M9D.nwb
WARNING:datajoint:Skipped checksum for file with hash: afad33a9-bda1-2343-aaee-3a8e07eab293, and path: /stelmo/nwb/analysis/eliot20221022/eliot20221022_A6ZIRB9M9D.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221022_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:50:08,759][WARNING]: Skipped checksum for file with hash: 7245398d-b0f5-4b0e-ed0b-69d5ee59ed79, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_8346BB677A.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7245398d-b0f5-4b0e-ed0b-69d5ee59ed79, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_8346BB677A.nwb

eliot20221023_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221023_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:50:16,507][WARNING]: Skipped checksum for file with hash: 219bdd51-204b-c4ca-2f49-9b7cff8563e9, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_7ALKEBLV1I.nwb
WARNING:datajoint:Skipped checksum for file with hash: 219bdd51-204b-c4ca-2f49-9b7cff8563e9, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_7ALKEBLV1I.nwb

Found remote theta in trial  [54, 54, 54, 54, 54, 54]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221023_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [14, 14]
Found remote theta in trial  [57, 57, 57]
Found remote theta in trial  [67]

[2026-01-25 20:50:24,297][WARNING]: Skipped checksum for file with hash: 997d2bfb-5a71-b692-99d4-e19fee2988ca, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_MT5HL6U06J.nwb
WARNING:datajoint:Skipped checksum for file with hash: 997d2bfb-5a71-b692-99d4-e19fee2988ca, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_MT5HL6U06J.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221023_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [26, 26, 26]
Found remote theta in trial  [47]

[2026-01-25 20:50:32,141][WARNING]: Skipped checksum for file with hash: 47d1fcbe-7ad0-40ad-6901-953332e2ac54, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_BH6W466TJP.nwb
WARNING:datajoint:Skipped checksum for file with hash: 47d1fcbe-7ad0-40ad-6901-953332e2ac54, and path: /stelmo/nwb/analysis/eliot20221023/eliot20221023_BH6W466TJP.nwb

Found remote theta in trial  [79, 79, 79]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221023_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [11]
Found remote theta in trial  [63, 63, 63, 63]
eliot20221024_.nwb

[2026-01-25 20:50:39,879][WARNING]: Skipped checksum for file with hash: 9f6108c6-e9e9-801e-65eb-8016714356fa, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_ERV0XGDPKO.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9f6108c6-e9e9-801e-65eb-8016714356fa, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_ERV0XGDPKO.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221024_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:50:47,469][WARNING]: Skipped checksum for file with hash: 05849536-e9de-a85e-ef63-bad709d57792, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_5CB7O4JH4V.nwb
WARNING:datajoint:Skipped checksum for file with hash: 05849536-e9de-a85e-ef63-bad709d57792, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_5CB7O4JH4V.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221024_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:50:55,459][WARNING]: Skipped checksum for file with hash: 05263a8d-e0fb-4825-4177-00b133c557ee, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_RW8AA9TKEX.nwb
WARNING:datajoint:Skipped checksum for file with hash: 05263a8d-e0fb-4825-4177-00b133c557ee, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_RW8AA9TKEX.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221024_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [13]
Found remote theta in trial  [19, 19]
Found remote theta in trial  [19, 19, 19, 19, 19]
Found remote theta in trial  [52]

[2026-01-25 20:51:03,711][WARNING]: Skipped checksum for file with hash: 036d9db0-8885-8433-588f-72a7f3c5c541, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_POQ2DPVGDS.nwb
WARNING:datajoint:Skipped checksum for file with hash: 036d9db0-8885-8433-588f-72a7f3c5c541, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_POQ2DPVGDS.nwb

Found remote theta in trial  [77, 77, 77]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221024_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:51:12,306][WARNING]: Skipped checksum for file with hash: 9f10bc91-de5e-ab49-08bb-e65ca9f63666, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_X42ZG0BY3I.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9f10bc91-de5e-ab49-08bb-e65ca9f63666, and path: /stelmo/nwb/analysis/eliot20221024/eliot20221024_X42ZG0BY3I.nwb

Found remote theta in trial  [58, 58, 58, 58, 58]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221024_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [7, 7]
Found remote theta in trial  [35, 35]
Found remote theta in trial  [42, 42, 42, 42, 42, 42, 42, 42, 42, 42]
Found remote theta in trial  [46]

[2026-01-25 20:51:21,029][WARNING]: Skipped checksum for file with hash: 02a30910-4cee-782c-40ec-59cdccc67058, and path: /stelmo/nwb/analysis/eliot20221025/eliot20221025_M3U1URQZDB.nwb
WARNING:datajoint:Skipped checksum for file with hash: 02a30910-4cee-782c-40ec-59cdccc67058, and path: /stelmo/nwb/analysis/eliot20221025/eliot20221025_M3U1URQZDB.nwb

Found remote theta in trial  [48, 48, 48]
eliot20221025_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221025_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [17]
Found remote theta in trial  [30, 30, 30]
Found remote theta in trial  [65]
Found remote theta in trial  [69, 69, 69]

[2026-01-25 20:51:30,352][WARNING]: Skipped checksum for file with hash: e06f403c-3156-8d0a-ae00-c857add3567e, and path: /stelmo/nwb/analysis/eliot20221025/eliot20221025_7I8GWP4SKD.nwb
WARNING:datajoint:Skipped checksum for file with hash: e06f403c-3156-8d0a-ae00-c857add3567e, and path: /stelmo/nwb/analysis/eliot20221025/eliot20221025_7I8GWP4SKD.nwb

Found remote theta in trial  [72, 72, 72, 72]
No triggered decode found for  {'nwb_file_name': 'eliot20221025_.nwb', 'epoch': 4, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221025_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:51:38,568][WARNING]: Skipped checksum for file with hash: 9a18ecc6-125c-1f7b-77b0-253d2d41078c, and path: /stelmo/nwb/analysis/eliot20221025/eliot20221025_VLLBRNO9BO.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9a18ecc6-125c-1f7b-77b0-253d2d41078c, and path: /stelmo/nwb/analysis/eliot20221025/eliot20221025_VLLBRNO9BO.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221025_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:51:46,729][WARNING]: Skipped checksum for file with hash: 487dd23e-bcf9-8f28-c682-387a4e3bf544, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_34BGCYI7ZA.nwb
WARNING:datajoint:Skipped checksum for file with hash: 487dd23e-bcf9-8f28-c682-387a4e3bf544, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_34BGCYI7ZA.nwb

Found remote theta in trial  [61]
eliot20221026_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221026_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:51:54,816][WARNING]: Skipped checksum for file with hash: 0daab4b8-ef64-ef22-456d-b022a2f3e660, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_LBSGRDRD0Y.nwb
WARNING:datajoint:Skipped checksum for file with hash: 0daab4b8-ef64-ef22-456d-b022a2f3e660, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_LBSGRDRD0Y.nwb

Found remote theta in trial  [19]
Found remote theta in trial  [36]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221026_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [8]
Found remote theta in trial  [10, 10]

[2026-01-25 20:52:02,937][WARNING]: Skipped checksum for file with hash: 497907ce-11d8-84f2-18bc-345e25b9253b, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_M9ZFUWRTHF.nwb
WARNING:datajoint:Skipped checksum for file with hash: 497907ce-11d8-84f2-18bc-345e25b9253b, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_M9ZFUWRTHF.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221026_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:52:11,498][WARNING]: Skipped checksum for file with hash: 76d8682b-b91d-3ea6-7a0e-bd615ff1dd24, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_ORSZT1XFKQ.nwb
WARNING:datajoint:Skipped checksum for file with hash: 76d8682b-b91d-3ea6-7a0e-bd615ff1dd24, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_ORSZT1XFKQ.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221026_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:52:19,423][WARNING]: Skipped checksum for file with hash: 334f72a8-9783-5483-2e0a-93751754ec39, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_XC54JOUE1P.nwb
WARNING:datajoint:Skipped checksum for file with hash: 334f72a8-9783-5483-2e0a-93751754ec39, and path: /stelmo/nwb/analysis/eliot20221026/eliot20221026_XC54JOUE1P.nwb

Found remote theta in trial  [41]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
eliot20221026_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:52:27,224][WARNING]: Skipped checksum for file with hash: 3e7b809f-2e3f-abe1-fb59-44a9a6f4ea54, and path: /stelmo/nwb/analysis/molly20220416/molly20220416_M0IQEYSPIQ.nwb
WARNING:datajoint:Skipped checksum for file with hash: 3e7b809f-2e3f-abe1-fb59-44a9a6f4ea54, and path: /stelmo/nwb/analysis/molly20220416/molly20220416_M0IQEYSPIQ.nwb

Found remote theta in trial  [16]
Found remote theta in trial  [19, 19]
No triggered decode found for  {'nwb_file_name': 'eliot20221026_.nwb', 'epoch': 12, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
molly20220416_.nwb
No triggered decode found for  {'nwb_file_name': 'molly20220416_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'molly20220416_.nwb', 'epoch': 4, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'molly20220416_.nwb', 'epoch': 6, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}

[2026-01-25 20:52:37,899][WARNING]: Skipped checksum for file with hash: af5e03c0-b5a0-56f0-e6f9-5d2698547feb, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_HS35HQ7SDN.nwb
WARNING:datajoint:Skipped checksum for file with hash: af5e03c0-b5a0-56f0-e6f9-5d2698547feb, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_HS35HQ7SDN.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220416_ 8         0.1                                         =BLOB=
 (Total: 1)

No triggered decode found for  {'nwb_file_name': 'molly20220416_.nwb', 'epoch': 10, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
molly20220417_.nwb

[2026-01-25 20:52:48,680][WARNING]: Skipped checksum for file with hash: 0fdc2151-c032-650c-0c27-5affff0abe88, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_YDKM6O2VKP.nwb
WARNING:datajoint:Skipped checksum for file with hash: 0fdc2151-c032-650c-0c27-5affff0abe88, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_YDKM6O2VKP.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220417_ 2         0.1                                         =BLOB=
 (Total: 1)

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220417_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:52:59,671][WARNING]: Skipped checksum for file with hash: e6d4f4ef-239a-5d7b-577a-a192af480a14, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_DZ0O86AH2L.nwb
WARNING:datajoint:Skipped checksum for file with hash: e6d4f4ef-239a-5d7b-577a-a192af480a14, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_DZ0O86AH2L.nwb

Found remote theta in trial  [59, 59, 59]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220417_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [20]

[2026-01-25 20:53:10,490][WARNING]: Skipped checksum for file with hash: 7a37fcff-bb75-7797-26f9-9bae17ada89a, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_N6CRX69WH7.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7a37fcff-bb75-7797-26f9-9bae17ada89a, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_N6CRX69WH7.nwb

Found remote theta in trial  [44, 44]
Found remote theta in trial  [60]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220417_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:53:21,208][WARNING]: Skipped checksum for file with hash: b662d7ce-df07-51dc-8e33-e9015ad6a070, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_XB5DX5A1I3.nwb
WARNING:datajoint:Skipped checksum for file with hash: b662d7ce-df07-51dc-8e33-e9015ad6a070, and path: /stelmo/nwb/analysis/molly20220417/molly20220417_XB5DX5A1I3.nwb

Found remote theta in trial  [50, 50, 50]
Found remote theta in trial  [63, 63, 63]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220417_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [15]
Found remote theta in trial  [36]
Found remote theta in trial  [50, 50, 50]
Found remote theta in trial  [50, 50, 50, 50]

[2026-01-25 20:53:32,383][WARNING]: Skipped checksum for file with hash: 1b0c911f-505a-f821-e9a4-8d9c7c583e01, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_H61UYU2M4J.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1b0c911f-505a-f821-e9a4-8d9c7c583e01, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_H61UYU2M4J.nwb

Found remote theta in trial  [50, 50]
Found remote theta in trial  [55, 55]
molly20220418_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220418_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [39]

[2026-01-25 20:53:43,626][WARNING]: Skipped checksum for file with hash: 3dcf58a9-b6b2-406f-8b19-ea76f039824b, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_QVRDN3O2I2.nwb
WARNING:datajoint:Skipped checksum for file with hash: 3dcf58a9-b6b2-406f-8b19-ea76f039824b, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_QVRDN3O2I2.nwb

Found remote theta in trial  [44, 44, 44]
Found remote theta in trial  [48]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220418_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:53:54,066][WARNING]: Skipped checksum for file with hash: d5371d48-1fca-424a-2591-229c1ef9b284, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_YJR8LLT6JB.nwb
WARNING:datajoint:Skipped checksum for file with hash: d5371d48-1fca-424a-2591-229c1ef9b284, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_YJR8LLT6JB.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220418_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [12]
Found remote theta in trial  [17]
Found remote theta in trial  [39, 39]
Found remote theta in trial  [48]
Found remote theta in trial  [53]

[2026-01-25 20:54:05,580][WARNING]: Skipped checksum for file with hash: 585af37a-28e6-f66a-ccdb-7571914a836a, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_FAAJJ08ZHN.nwb
WARNING:datajoint:Skipped checksum for file with hash: 585af37a-28e6-f66a-ccdb-7571914a836a, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_FAAJJ08ZHN.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220418_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [17]
Found remote theta in trial  [65, 65]

[2026-01-25 20:54:16,691][WARNING]: Skipped checksum for file with hash: b5bf1b83-5960-8694-dc07-1a6bc1f361c0, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_507ICA2C6Z.nwb
WARNING:datajoint:Skipped checksum for file with hash: b5bf1b83-5960-8694-dc07-1a6bc1f361c0, and path: /stelmo/nwb/analysis/molly20220418/molly20220418_507ICA2C6Z.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220418_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [22, 22, 22]
Found remote theta in trial  [28, 28, 28, 28]
Found remote theta in trial  [34, 34, 34, 34, 34]

[2026-01-25 20:54:28,104][WARNING]: Skipped checksum for file with hash: 8d998187-4fc2-b703-cdb6-f8742a719423, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_L7FMYY7ZV3.nwb
WARNING:datajoint:Skipped checksum for file with hash: 8d998187-4fc2-b703-cdb6-f8742a719423, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_L7FMYY7ZV3.nwb

Found remote theta in trial  [39]
Found remote theta in trial  [68]
molly20220419_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220419_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [32, 32]
Found remote theta in trial  [32]
Found remote theta in trial  [45]
Found remote theta in trial  [52, 52, 52, 52]

[2026-01-25 20:54:39,634][WARNING]: Skipped checksum for file with hash: b435a8f9-f5f7-e3c4-a229-b1bff123e49d, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_NKKFGI0NAX.nwb
WARNING:datajoint:Skipped checksum for file with hash: b435a8f9-f5f7-e3c4-a229-b1bff123e49d, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_NKKFGI0NAX.nwb

Found remote theta in trial  [59, 59, 59, 59, 59, 59]
Found remote theta in trial  [60, 60]
Found remote theta in trial  [76]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220419_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [23]

[2026-01-25 20:54:50,812][WARNING]: Skipped checksum for file with hash: d964f652-93e2-7611-499e-7f783ea90ba6, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_HEVHY6VW04.nwb
WARNING:datajoint:Skipped checksum for file with hash: d964f652-93e2-7611-499e-7f783ea90ba6, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_HEVHY6VW04.nwb

Found remote theta in trial  [38, 38, 38]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220419_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [8, 8, 8]

[2026-01-25 20:55:01,921][WARNING]: Skipped checksum for file with hash: b7953325-c6fc-8e45-3732-361284615c15, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_7FQ0H3U5B6.nwb
WARNING:datajoint:Skipped checksum for file with hash: b7953325-c6fc-8e45-3732-361284615c15, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_7FQ0H3U5B6.nwb

Found remote theta in trial  [50, 50, 50, 50]
Found remote theta in trial  [71, 71, 71, 71, 71, 71]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220419_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:55:12,758][WARNING]: Skipped checksum for file with hash: 4105a9cf-ac5b-09ee-3ba5-0806b3d3df0c, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_XVQ21BTJZU.nwb
WARNING:datajoint:Skipped checksum for file with hash: 4105a9cf-ac5b-09ee-3ba5-0806b3d3df0c, and path: /stelmo/nwb/analysis/molly20220419/molly20220419_XVQ21BTJZU.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220419_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:55:23,800][WARNING]: Skipped checksum for file with hash: 73e99265-19d0-7f7c-59b4-c2a8edcce355, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_C7KSRDHN97.nwb
WARNING:datajoint:Skipped checksum for file with hash: 73e99265-19d0-7f7c-59b4-c2a8edcce355, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_C7KSRDHN97.nwb

Found remote theta in trial  [23, 23, 23, 23]
Found remote theta in trial  [23]
molly20220420_.nwb
No triggered decode found for  {'nwb_file_name': 'molly20220420_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220420_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:55:35,204][WARNING]: Skipped checksum for file with hash: b1d1cf76-f57d-33c5-74d6-c3689e886b57, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_U54B0DPWS1.nwb
WARNING:datajoint:Skipped checksum for file with hash: b1d1cf76-f57d-33c5-74d6-c3689e886b57, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_U54B0DPWS1.nwb

Found remote theta in trial  [73, 73, 73]
Found remote theta in trial  [76, 76]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220420_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:55:46,393][WARNING]: Skipped checksum for file with hash: fc8e6518-87b5-e729-26a9-ed614ee06f4d, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_I7TTUA6O3Z.nwb
WARNING:datajoint:Skipped checksum for file with hash: fc8e6518-87b5-e729-26a9-ed614ee06f4d, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_I7TTUA6O3Z.nwb

Found remote theta in trial  [59]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220420_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [20]
Found remote theta in trial  [62]
Found remote theta in trial  [63, 63]
Found remote theta in trial  [64, 64, 64, 64]

[2026-01-25 20:55:57,946][WARNING]: Skipped checksum for file with hash: 3def622a-a07c-8efa-7ab8-a7afd748207b, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_2CILRSN5UD.nwb
WARNING:datajoint:Skipped checksum for file with hash: 3def622a-a07c-8efa-7ab8-a7afd748207b, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_2CILRSN5UD.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220420_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [20, 20]
Found remote theta in trial  [55, 55, 55]
Found remote theta in trial  [66, 66, 66, 66]
Found remote theta in trial  [73]

[2026-01-25 20:56:09,493][WARNING]: Skipped checksum for file with hash: 3ff99621-6d86-1738-b5b9-504619c89bbf, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_IB1R2U9PEH.nwb
WARNING:datajoint:Skipped checksum for file with hash: 3ff99621-6d86-1738-b5b9-504619c89bbf, and path: /stelmo/nwb/analysis/molly20220420/molly20220420_IB1R2U9PEH.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
molly20220420_ 12        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [29, 29]

[2026-01-25 20:56:20,675][WARNING]: Skipped checksum for file with hash: 7c1e9197-6354-6163-ab33-f66bca816747, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_KJOOXRWKVQ.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7c1e9197-6354-6163-ab33-f66bca816747, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_KJOOXRWKVQ.nwb

Found remote theta in trial  [72]
klein20231101_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231101_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [5, 5]
Found remote theta in trial  [5]
Found remote theta in trial  [11, 11, 11, 11]
Found remote theta in trial  [14, 14]
Found remote theta in trial  [40]
Found remote theta in trial  [67]
Found remote theta in trial  [67]
Found remote theta in trial  [67]
Found remote theta in trial  [77, 77]

[2026-01-25 20:56:34,444][WARNING]: Skipped checksum for file with hash: 4616d3a3-4cbb-82ab-3a1b-b72f94cf4160, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_67PHRQDDVX.nwb
WARNING:datajoint:Skipped checksum for file with hash: 4616d3a3-4cbb-82ab-3a1b-b72f94cf4160, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_67PHRQDDVX.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231101_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [3]
Found remote theta in trial  [10, 10, 10, 10, 10]
Found remote theta in trial  [17, 17, 17]
Found remote theta in trial  [29]
Found remote theta in trial  [49]
Found remote theta in trial  [55, 55]

[2026-01-25 20:56:48,557][WARNING]: Skipped checksum for file with hash: 767c76f9-f456-d763-2f6a-7b7ecc754546, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_F68XZ5NKE7.nwb
WARNING:datajoint:Skipped checksum for file with hash: 767c76f9-f456-d763-2f6a-7b7ecc754546, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_F68XZ5NKE7.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231101_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [26, 26, 26]
Found remote theta in trial  [32, 32, 32]
Found remote theta in trial  [41, 41]
Found remote theta in trial  [43]
Found remote theta in trial  [54, 54]
Found remote theta in trial  [54]

[2026-01-25 20:57:02,245][WARNING]: Skipped checksum for file with hash: 5f098583-6011-78d9-f806-1b459a44b0a9, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_NCKCKDDZO9.nwb
WARNING:datajoint:Skipped checksum for file with hash: 5f098583-6011-78d9-f806-1b459a44b0a9, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_NCKCKDDZO9.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231101_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [5, 5]
Found remote theta in trial  [7]
Found remote theta in trial  [8]
Found remote theta in trial  [17, 17]

[2026-01-25 20:57:16,691][WARNING]: Skipped checksum for file with hash: 1f013afc-9610-30e0-139a-3e6494fc579c, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_D9LG5VQ7BU.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1f013afc-9610-30e0-139a-3e6494fc579c, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_D9LG5VQ7BU.nwb

Found remote theta in trial  [70]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231101_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [35]
Found remote theta in trial  [75]
Found remote theta in trial  [75, 75]

[2026-01-25 20:57:30,579][WARNING]: Skipped checksum for file with hash: 58de295e-321d-28c2-01ae-3c798c799e62, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_OVSFU5HI62.nwb
WARNING:datajoint:Skipped checksum for file with hash: 58de295e-321d-28c2-01ae-3c798c799e62, and path: /stelmo/nwb/analysis/klein20231101/klein20231101_OVSFU5HI62.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231101_ 12        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [14, 14]
Found remote theta in trial  [20, 20, 20]
Found remote theta in trial  [20, 20, 20, 20, 20, 20, 20]
Found remote theta in trial  [20, 20, 20, 20, 20]
Found remote theta in trial  [28]
Found remote theta in trial  [55]

[2026-01-25 20:57:45,223][WARNING]: Skipped checksum for file with hash: 7019f357-6d85-87a2-7f3d-05c3d9403556, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_LBNJH4SOH3.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7019f357-6d85-87a2-7f3d-05c3d9403556, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_LBNJH4SOH3.nwb

Found remote theta in trial  [64]
klein20231102_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231102_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [34, 34]
Found remote theta in trial  [53, 53]
Found remote theta in trial  [72]
Found remote theta in trial  [72]

[2026-01-25 20:57:58,333][WARNING]: Skipped checksum for file with hash: 404f3fc2-3b6b-1b7d-7099-21cb14e43bd8, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_5O9S7G9BCX.nwb
WARNING:datajoint:Skipped checksum for file with hash: 404f3fc2-3b6b-1b7d-7099-21cb14e43bd8, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_5O9S7G9BCX.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231102_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [15, 15]
Found remote theta in trial  [28, 28, 28]

[2026-01-25 20:58:10,818][WARNING]: Skipped checksum for file with hash: 0005367e-8c00-4ebf-9888-a9bb8b57ef24, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_ST2UO7R2NI.nwb
WARNING:datajoint:Skipped checksum for file with hash: 0005367e-8c00-4ebf-9888-a9bb8b57ef24, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_ST2UO7R2NI.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231102_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [8, 8]

[2026-01-25 20:58:23,299][WARNING]: Skipped checksum for file with hash: 9e786399-1cdb-14e1-447d-4953b0e079b2, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_BCJFRYL3CV.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9e786399-1cdb-14e1-447d-4953b0e079b2, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_BCJFRYL3CV.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231102_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [2]
Found remote theta in trial  [43]
Found remote theta in trial  [50, 50]
Found remote theta in trial  [50]
Found remote theta in trial  [60]
Found remote theta in trial  [73]
Found remote theta in trial  [79]

[2026-01-25 20:58:35,961][WARNING]: Skipped checksum for file with hash: 23b5413b-0d75-75c5-3141-c6687afa44ae, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_S9O78UKCYW.nwb
WARNING:datajoint:Skipped checksum for file with hash: 23b5413b-0d75-75c5-3141-c6687afa44ae, and path: /stelmo/nwb/analysis/klein20231102/klein20231102_S9O78UKCYW.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231102_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [10, 10, 10]
Found remote theta in trial  [39, 39, 39]
Found remote theta in trial  [39, 39, 39]
Found remote theta in trial  [39, 39, 39, 39, 39, 39, 39, 39, 39]
Found remote theta in trial  [39, 39, 39, 39, 39, 39]
Found remote theta in trial  [67]
Found remote theta in trial  [73]
Found remote theta in trial  [73, 73, 73]

[2026-01-25 20:58:49,822][WARNING]: Skipped checksum for file with hash: 94ca79c5-68b2-4efc-6aa8-4e060dd5b7fc, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_6F1CEFZYS3.nwb
WARNING:datajoint:Skipped checksum for file with hash: 94ca79c5-68b2-4efc-6aa8-4e060dd5b7fc, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_6F1CEFZYS3.nwb

Found remote theta in trial  [77, 77]
klein20231103_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231103_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:59:01,670][WARNING]: Skipped checksum for file with hash: 85ca4349-8b5a-fe3b-e0e5-35b207db5e33, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_O3L1M8AW36.nwb
WARNING:datajoint:Skipped checksum for file with hash: 85ca4349-8b5a-fe3b-e0e5-35b207db5e33, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_O3L1M8AW36.nwb

Found remote theta in trial  [42, 42]
Found remote theta in trial  [42]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231103_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 20:59:11,851][WARNING]: Skipped checksum for file with hash: 808affae-ed99-a434-83df-836fbf91ecc2, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_FBPXURW1MI.nwb
WARNING:datajoint:Skipped checksum for file with hash: 808affae-ed99-a434-83df-836fbf91ecc2, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_FBPXURW1MI.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231103_ 5         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [38]
Found remote theta in trial  [46]
Found remote theta in trial  [52]
Found remote theta in trial  [60]

[2026-01-25 20:59:24,180][WARNING]: Skipped checksum for file with hash: deb820c1-0f6a-4db6-cc5d-16cea95890c6, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_PBLTAAW5NC.nwb
WARNING:datajoint:Skipped checksum for file with hash: deb820c1-0f6a-4db6-cc5d-16cea95890c6, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_PBLTAAW5NC.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231103_ 7         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [9, 9]
Found remote theta in trial  [10, 10]
Found remote theta in trial  [22, 22, 22, 22, 22, 22]
Found remote theta in trial  [23]
Found remote theta in trial  [23, 23, 23, 23]
Found remote theta in trial  [23, 23, 23]

[2026-01-25 20:59:36,641][WARNING]: Skipped checksum for file with hash: 210fca95-4155-1949-a9be-5860f2d792df, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_NKX5U80F6Q.nwb
WARNING:datajoint:Skipped checksum for file with hash: 210fca95-4155-1949-a9be-5860f2d792df, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_NKX5U80F6Q.nwb

Found remote theta in trial  [60, 60]
Found remote theta in trial  [76]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231103_ 9         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [15, 15, 15]
Found remote theta in trial  [22]
Found remote theta in trial  [72]

[2026-01-25 20:59:48,835][WARNING]: Skipped checksum for file with hash: 734a7301-73a1-944a-b10e-f32e28c56f06, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_ZCHHAEYUEV.nwb
WARNING:datajoint:Skipped checksum for file with hash: 734a7301-73a1-944a-b10e-f32e28c56f06, and path: /stelmo/nwb/analysis/klein20231103/klein20231103_ZCHHAEYUEV.nwb

Found remote theta in trial  [72, 72, 72, 72, 72]
Found remote theta in trial  [73]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231103_ 11        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [13, 13, 13]
Found remote theta in trial  [44, 44, 44, 44, 44]

[2026-01-25 21:00:01,105][WARNING]: Skipped checksum for file with hash: d6eba197-e118-5908-6c4d-10cd45c2ee4b, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_O97LNA1R5P.nwb
WARNING:datajoint:Skipped checksum for file with hash: d6eba197-e118-5908-6c4d-10cd45c2ee4b, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_O97LNA1R5P.nwb

Found remote theta in trial  [77]
klein20231104_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231104_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [30]
Found remote theta in trial  [46]

[2026-01-25 21:00:13,100][WARNING]: Skipped checksum for file with hash: 385f77c9-cca9-12d1-9e33-078daeb17357, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_0MIHZMVQI5.nwb
WARNING:datajoint:Skipped checksum for file with hash: 385f77c9-cca9-12d1-9e33-078daeb17357, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_0MIHZMVQI5.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231104_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [16, 16, 16]
Found remote theta in trial  [27]
Found remote theta in trial  [37, 37]
Found remote theta in trial  [48]
Found remote theta in trial  [49, 49]

[2026-01-25 21:00:26,283][WARNING]: Skipped checksum for file with hash: be2343b8-dd0b-0ecd-1127-b4ea04e871c3, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_1JI35RXDNR.nwb
WARNING:datajoint:Skipped checksum for file with hash: be2343b8-dd0b-0ecd-1127-b4ea04e871c3, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_1JI35RXDNR.nwb

Found remote theta in trial  [67, 67, 67, 67]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231104_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [28, 28, 28, 28]
Found remote theta in trial  [37, 37, 37, 37]
Found remote theta in trial  [37]
Found remote theta in trial  [38, 38]
Found remote theta in trial  [49, 49]
Found remote theta in trial  [63, 63, 63]

[2026-01-25 21:00:39,774][WARNING]: Skipped checksum for file with hash: 017f56a4-2160-3ef7-5233-e5718da980e0, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_C1LOSOH13A.nwb
WARNING:datajoint:Skipped checksum for file with hash: 017f56a4-2160-3ef7-5233-e5718da980e0, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_C1LOSOH13A.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231104_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [2]
Found remote theta in trial  [36, 36, 36]

[2026-01-25 21:00:52,171][WARNING]: Skipped checksum for file with hash: a4dcc24c-92bc-c3f0-92e8-89d6117db1eb, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_OKTEBPBNLH.nwb
WARNING:datajoint:Skipped checksum for file with hash: a4dcc24c-92bc-c3f0-92e8-89d6117db1eb, and path: /stelmo/nwb/analysis/klein20231104/klein20231104_OKTEBPBNLH.nwb

Found remote theta in trial  [36, 36]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231104_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [8, 8]
Found remote theta in trial  [51, 51, 51]
Found remote theta in trial  [75]
Found remote theta in trial  [75, 75]

[2026-01-25 21:01:04,496][WARNING]: Skipped checksum for file with hash: e27d92a9-9f0b-5e00-be65-edf746610349, and path: /stelmo/nwb/analysis/klein20231105/klein20231105_T6EZYZG7CU.nwb
WARNING:datajoint:Skipped checksum for file with hash: e27d92a9-9f0b-5e00-be65-edf746610349, and path: /stelmo/nwb/analysis/klein20231105/klein20231105_T6EZYZG7CU.nwb

klein20231105_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231105_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [50, 50, 50]
Found remote theta in trial  [78]
Found remote theta in trial  [78]

[2026-01-25 21:01:16,620][WARNING]: Skipped checksum for file with hash: dd19b8ed-eed1-2353-cb7f-c1bfc2d22299, and path: /stelmo/nwb/analysis/klein20231105/klein20231105_YRNQL93KSM.nwb
WARNING:datajoint:Skipped checksum for file with hash: dd19b8ed-eed1-2353-cb7f-c1bfc2d22299, and path: /stelmo/nwb/analysis/klein20231105/klein20231105_YRNQL93KSM.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231105_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [11, 11]

[2026-01-25 21:01:28,890][WARNING]: Skipped checksum for file with hash: d52a1065-3813-ae1a-9885-9bb8997a85cf, and path: /stelmo/nwb/analysis/klein20231105/klein20231105_G4XID7QM6V.nwb
WARNING:datajoint:Skipped checksum for file with hash: d52a1065-3813-ae1a-9885-9bb8997a85cf, and path: /stelmo/nwb/analysis/klein20231105/klein20231105_G4XID7QM6V.nwb

Found remote theta in trial  [23]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231105_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [17]
Found remote theta in trial  [30, 30, 30, 30, 30]
Found remote theta in trial  [46, 46, 46]

[2026-01-25 21:01:41,313][WARNING]: Skipped checksum for file with hash: 49a1be2c-654e-9a2b-eb6a-d40cf998f612, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_WQQFFHEHCG.nwb
WARNING:datajoint:Skipped checksum for file with hash: 49a1be2c-654e-9a2b-eb6a-d40cf998f612, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_WQQFFHEHCG.nwb

Found remote theta in trial  [80, 80, 80]
No triggered decode found for  {'nwb_file_name': 'klein20231105_.nwb', 'epoch': 8, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
klein20231106_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231106_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:01:53,038][WARNING]: Skipped checksum for file with hash: 62868424-1b6a-c2ad-e13a-34bcc526e664, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_GK5YPCDZRG.nwb
WARNING:datajoint:Skipped checksum for file with hash: 62868424-1b6a-c2ad-e13a-34bcc526e664, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_GK5YPCDZRG.nwb

Found remote theta in trial  [25, 25]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231106_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [29, 29]

[2026-01-25 21:02:05,431][WARNING]: Skipped checksum for file with hash: 51f0c350-adf5-ea1b-155b-7724ddc0e489, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_K2YMR18MTY.nwb
WARNING:datajoint:Skipped checksum for file with hash: 51f0c350-adf5-ea1b-155b-7724ddc0e489, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_K2YMR18MTY.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231106_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:02:16,906][WARNING]: Skipped checksum for file with hash: 727f1fa7-332f-f4cf-32cd-5316caca911f, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_6G2EKZ6I46.nwb
WARNING:datajoint:Skipped checksum for file with hash: 727f1fa7-332f-f4cf-32cd-5316caca911f, and path: /stelmo/nwb/analysis/klein20231106/klein20231106_6G2EKZ6I46.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231106_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:02:28,548][WARNING]: Skipped checksum for file with hash: e4679029-0ed2-1886-c3a6-4cc24766e0ba, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_045WWJH608.nwb
WARNING:datajoint:Skipped checksum for file with hash: e4679029-0ed2-1886-c3a6-4cc24766e0ba, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_045WWJH608.nwb

klein20231107_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231107_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [29]
Found remote theta in trial  [56]
Found remote theta in trial  [62]
Found remote theta in trial  [71, 71]
Found remote theta in trial  [71]

[2026-01-25 21:02:41,625][WARNING]: Skipped checksum for file with hash: 1631506f-15b6-034c-5145-75071caff81c, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_33XWZW5ZX0.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1631506f-15b6-034c-5145-75071caff81c, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_33XWZW5ZX0.nwb

Found remote theta in trial  [72]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231107_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [11]
Found remote theta in trial  [11, 11, 11]
Found remote theta in trial  [11, 11]
Found remote theta in trial  [11, 11, 11]
Found remote theta in trial  [64]
Found remote theta in trial  [65]
Found remote theta in trial  [71, 71, 71, 71]

[2026-01-25 21:02:54,441][WARNING]: Skipped checksum for file with hash: 8981104c-b0c1-9e58-669d-d10766de76bd, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_F57Z85ENAK.nwb
WARNING:datajoint:Skipped checksum for file with hash: 8981104c-b0c1-9e58-669d-d10766de76bd, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_F57Z85ENAK.nwb

Found remote theta in trial  [78]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231107_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:03:06,447][WARNING]: Skipped checksum for file with hash: ea6cdf57-0a7c-5f88-0db7-d6ff33174ac0, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_FDF650YL9G.nwb
WARNING:datajoint:Skipped checksum for file with hash: ea6cdf57-0a7c-5f88-0db7-d6ff33174ac0, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_FDF650YL9G.nwb

Found remote theta in trial  [69, 69, 69]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231107_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [28, 28]
Found remote theta in trial  [39]
Found remote theta in trial  [43]

[2026-01-25 21:03:18,708][WARNING]: Skipped checksum for file with hash: 62e7771d-a5b2-b0ca-74a0-0ace0d491e3b, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_W4OUG1EJ4Z.nwb
WARNING:datajoint:Skipped checksum for file with hash: 62e7771d-a5b2-b0ca-74a0-0ace0d491e3b, and path: /stelmo/nwb/analysis/klein20231107/klein20231107_W4OUG1EJ4Z.nwb

Found remote theta in trial  [66]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231107_ 10        0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [28, 28]
Found remote theta in trial  [34]
Found remote theta in trial  [61, 61]

[2026-01-25 21:03:30,913][WARNING]: Skipped checksum for file with hash: cf2e09b0-f55f-6ad6-af30-5fd718218d57, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_TOR4EAPYX9.nwb
WARNING:datajoint:Skipped checksum for file with hash: cf2e09b0-f55f-6ad6-af30-5fd718218d57, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_TOR4EAPYX9.nwb

Found remote theta in trial  [74]
Found remote theta in trial  [79, 79]
klein20231108_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231108_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [20, 20, 20]
Found remote theta in trial  [29, 29]
Found remote theta in trial  [29, 29, 29, 29]

[2026-01-25 21:03:43,699][WARNING]: Skipped checksum for file with hash: 4b2f9e56-9ca9-b150-2aef-c1ca683bce2a, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_RNYUPCWXMR.nwb
WARNING:datajoint:Skipped checksum for file with hash: 4b2f9e56-9ca9-b150-2aef-c1ca683bce2a, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_RNYUPCWXMR.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231108_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:03:55,716][WARNING]: Skipped checksum for file with hash: c43775bb-faf9-e160-3d96-8628bc783452, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_C7QET3XYMV.nwb
WARNING:datajoint:Skipped checksum for file with hash: c43775bb-faf9-e160-3d96-8628bc783452, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_C7QET3XYMV.nwb

Found remote theta in trial  [51, 51]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231108_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:04:07,563][WARNING]: Skipped checksum for file with hash: 25d4d282-dd7a-ddbb-ec09-27070063ed7a, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_GJSV5X61LI.nwb
WARNING:datajoint:Skipped checksum for file with hash: 25d4d282-dd7a-ddbb-ec09-27070063ed7a, and path: /stelmo/nwb/analysis/klein20231108/klein20231108_GJSV5X61LI.nwb

Found remote theta in trial  [15]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
klein20231108_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [54]

[2026-01-25 21:04:19,663][WARNING]: Skipped checksum for file with hash: ac76da4d-7521-3a33-9446-52fb3eec89e5, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_KPYWTZC47T.nwb
WARNING:datajoint:Skipped checksum for file with hash: ac76da4d-7521-3a33-9446-52fb3eec89e5, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_KPYWTZC47T.nwb

julio20230731_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230731_ 2         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [22, 22, 22]

[2026-01-25 21:04:32,772][WARNING]: Skipped checksum for file with hash: e479e2bf-1b44-d4c0-4080-80e43ad0f505, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_0XBLBSVKGO.nwb
WARNING:datajoint:Skipped checksum for file with hash: e479e2bf-1b44-d4c0-4080-80e43ad0f505, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_0XBLBSVKGO.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230731_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [15, 15, 15]

[2026-01-25 21:04:46,059][WARNING]: Skipped checksum for file with hash: 7231318f-abac-008c-b9f3-eb9bbe14f4fe, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_M6RY9QNNEY.nwb
WARNING:datajoint:Skipped checksum for file with hash: 7231318f-abac-008c-b9f3-eb9bbe14f4fe, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_M6RY9QNNEY.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230731_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:04:57,821][WARNING]: Skipped checksum for file with hash: d3d80670-d7b8-3859-8c33-77bf78f7d7d9, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_THFHTEPHZG.nwb
WARNING:datajoint:Skipped checksum for file with hash: d3d80670-d7b8-3859-8c33-77bf78f7d7d9, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_THFHTEPHZG.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230731_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:05:10,544][WARNING]: Skipped checksum for file with hash: aa5bba43-1ba6-1b6f-cf8c-755caad3805e, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_14781BUN3S.nwb
WARNING:datajoint:Skipped checksum for file with hash: aa5bba43-1ba6-1b6f-cf8c-755caad3805e, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_14781BUN3S.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230731_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:05:24,203][WARNING]: Skipped checksum for file with hash: 0b2adc1d-7760-935a-2b1d-f5a20beecee8, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_54YUF1G0VX.nwb
WARNING:datajoint:Skipped checksum for file with hash: 0b2adc1d-7760-935a-2b1d-f5a20beecee8, and path: /stelmo/nwb/analysis/julio20230731/julio20230731_54YUF1G0VX.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230731_ 12        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:05:37,572][WARNING]: Skipped checksum for file with hash: 6569f592-8c90-6bb2-ccb8-8ad330caef4b, and path: /stelmo/nwb/analysis/julio20230801/julio20230801_GWH12PJEH7.nwb
WARNING:datajoint:Skipped checksum for file with hash: 6569f592-8c90-6bb2-ccb8-8ad330caef4b, and path: /stelmo/nwb/analysis/julio20230801/julio20230801_GWH12PJEH7.nwb

julio20230801_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230801_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230801_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:05:50,247][WARNING]: Skipped checksum for file with hash: 99227a51-924b-6eef-f5ab-db22f622b14c, and path: /stelmo/nwb/analysis/julio20230801/julio20230801_393220W3LN.nwb
WARNING:datajoint:Skipped checksum for file with hash: 99227a51-924b-6eef-f5ab-db22f622b14c, and path: /stelmo/nwb/analysis/julio20230801/julio20230801_393220W3LN.nwb

Found remote theta in trial  [16]
No triggered decode found for  {'nwb_file_name': 'julio20230801_.nwb', 'epoch': 6, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230801_.nwb', 'epoch': 8, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230801_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:06:02,352][WARNING]: Skipped checksum for file with hash: 1f71814c-eb47-f790-c8e1-bbb212b3403a, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_SHLIL3R36M.nwb
WARNING:datajoint:Skipped checksum for file with hash: 1f71814c-eb47-f790-c8e1-bbb212b3403a, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_SHLIL3R36M.nwb

No triggered decode found for  {'nwb_file_name': 'julio20230801_.nwb', 'epoch': 12, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
julio20230802_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230802_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:06:15,409][WARNING]: Skipped checksum for file with hash: 920e367d-9489-7e35-b141-d27223260209, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_0IYGC0K5Q1.nwb
WARNING:datajoint:Skipped checksum for file with hash: 920e367d-9489-7e35-b141-d27223260209, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_0IYGC0K5Q1.nwb

Found remote theta in trial  [77]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230802_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:06:27,911][WARNING]: Skipped checksum for file with hash: bc7d42e8-b536-edf6-6856-6173af1d1366, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_40NDKQJ0ND.nwb
WARNING:datajoint:Skipped checksum for file with hash: bc7d42e8-b536-edf6-6856-6173af1d1366, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_40NDKQJ0ND.nwb

Found remote theta in trial  [70, 70, 70]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230802_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [38]
Found remote theta in trial  [51, 51, 51, 51]
Found remote theta in trial  [69]

[2026-01-25 21:06:40,525][WARNING]: Skipped checksum for file with hash: 87415e7d-1b74-d9b6-2a09-a67d53cb1a0c, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_3EADYR45XE.nwb
WARNING:datajoint:Skipped checksum for file with hash: 87415e7d-1b74-d9b6-2a09-a67d53cb1a0c, and path: /stelmo/nwb/analysis/julio20230802/julio20230802_3EADYR45XE.nwb

Found remote theta in trial  [69, 69, 69]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230802_ 8         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [29]
Found remote theta in trial  [70]

[2026-01-25 21:06:52,867][WARNING]: Skipped checksum for file with hash: 2c0c8e36-6803-f39c-2c12-c19a1d9c0f9c, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_5VGNANULFD.nwb
WARNING:datajoint:Skipped checksum for file with hash: 2c0c8e36-6803-f39c-2c12-c19a1d9c0f9c, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_5VGNANULFD.nwb

julio20230803_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230803_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230803_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:07:05,522][WARNING]: Skipped checksum for file with hash: 337c9af5-ed6f-09dd-5f62-339fbeade9fe, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_7BF71KTLI4.nwb
WARNING:datajoint:Skipped checksum for file with hash: 337c9af5-ed6f-09dd-5f62-339fbeade9fe, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_7BF71KTLI4.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230803_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:07:18,028][WARNING]: Skipped checksum for file with hash: f94bbcda-0231-126d-e803-657c4b335e58, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_Q84JHQP4AB.nwb
WARNING:datajoint:Skipped checksum for file with hash: f94bbcda-0231-126d-e803-657c4b335e58, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_Q84JHQP4AB.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230803_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:07:31,078][WARNING]: Skipped checksum for file with hash: 4e0e2add-25fb-25a8-16cd-06e0f60d1698, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_DCG255URGG.nwb
WARNING:datajoint:Skipped checksum for file with hash: 4e0e2add-25fb-25a8-16cd-06e0f60d1698, and path: /stelmo/nwb/analysis/julio20230803/julio20230803_DCG255URGG.nwb

Found remote theta in trial  [51, 51, 51, 51]
Found remote theta in trial  [80, 80, 80, 80, 80, 80]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230803_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:07:42,385][WARNING]: Skipped checksum for file with hash: acf60b38-88f7-1813-9d48-bcc3c267f56a, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_7T7XUSVDKG.nwb
WARNING:datajoint:Skipped checksum for file with hash: acf60b38-88f7-1813-9d48-bcc3c267f56a, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_7T7XUSVDKG.nwb

Found remote theta in trial  [9, 9, 9, 9]
Found remote theta in trial  [69]
Found remote theta in trial  [69]
No triggered decode found for  {'nwb_file_name': 'julio20230803_.nwb', 'epoch': 12, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
julio20230804_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230804_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230804_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:07:53,942][WARNING]: Skipped checksum for file with hash: 9a3542ad-42ab-0bc9-f2b7-73a6e3019283, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_KK2QRLS8T1.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9a3542ad-42ab-0bc9-f2b7-73a6e3019283, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_KK2QRLS8T1.nwb

Found remote theta in trial  [70, 70, 70]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230804_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:08:05,249][WARNING]: Skipped checksum for file with hash: ccef3ff7-29b2-f3dc-966b-dc65428f3f1b, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_P8S7FXYQY2.nwb
WARNING:datajoint:Skipped checksum for file with hash: ccef3ff7-29b2-f3dc-966b-dc65428f3f1b, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_P8S7FXYQY2.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230804_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:08:16,830][WARNING]: Skipped checksum for file with hash: c9baacc8-cc02-d2ae-faea-41783093d501, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_Z118OB3VNL.nwb
WARNING:datajoint:Skipped checksum for file with hash: c9baacc8-cc02-d2ae-faea-41783093d501, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_Z118OB3VNL.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230804_ 10        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:08:27,993][WARNING]: Skipped checksum for file with hash: a3fb7557-9fab-2e0c-52a0-6290425a129a, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_TOS77VK6N5.nwb
WARNING:datajoint:Skipped checksum for file with hash: a3fb7557-9fab-2e0c-52a0-6290425a129a, and path: /stelmo/nwb/analysis/julio20230804/julio20230804_TOS77VK6N5.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230804_ 12        0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:08:38,990][WARNING]: Skipped checksum for file with hash: d768398a-af4c-588e-93a5-95b0b858f6e2, and path: /stelmo/nwb/analysis/julio20230805/julio20230805_F5SVP0WIGQ.nwb
WARNING:datajoint:Skipped checksum for file with hash: d768398a-af4c-588e-93a5-95b0b858f6e2, and path: /stelmo/nwb/analysis/julio20230805/julio20230805_F5SVP0WIGQ.nwb

Found remote theta in trial  [16]
julio20230805_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230805_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:08:50,514][WARNING]: Skipped checksum for file with hash: af0c7e41-2997-7d91-3a6b-1984f215fa86, and path: /stelmo/nwb/analysis/julio20230805/julio20230805_ZZ8P07AUYP.nwb
WARNING:datajoint:Skipped checksum for file with hash: af0c7e41-2997-7d91-3a6b-1984f215fa86, and path: /stelmo/nwb/analysis/julio20230805/julio20230805_ZZ8P07AUYP.nwb

Found remote theta in trial  [78, 78]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230805_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [20, 20, 20, 20, 20]
Found remote theta in trial  [27, 27, 27, 27]
Found remote theta in trial  [78]
Found remote theta in trial  [80]

[2026-01-25 21:09:02,185][WARNING]: Skipped checksum for file with hash: 74ad712f-077b-1635-3403-3777f2213976, and path: /stelmo/nwb/analysis/julio20230806/julio20230806_D4XO8VBZTQ.nwb
WARNING:datajoint:Skipped checksum for file with hash: 74ad712f-077b-1635-3403-3777f2213976, and path: /stelmo/nwb/analysis/julio20230806/julio20230806_D4XO8VBZTQ.nwb

No triggered decode found for  {'nwb_file_name': 'julio20230805_.nwb', 'epoch': 6, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230805_.nwb', 'epoch': 7, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230805_.nwb', 'epoch': 9, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
julio20230806_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230806_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230806_.nwb', 'epoch': 4, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230806_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:09:13,555][WARNING]: Skipped checksum for file with hash: 546d2bfb-ff34-1141-b095-0f82d8a86474, and path: /stelmo/nwb/analysis/julio20230806/julio20230806_R2IZLN6PKN.nwb
WARNING:datajoint:Skipped checksum for file with hash: 546d2bfb-ff34-1141-b095-0f82d8a86474, and path: /stelmo/nwb/analysis/julio20230806/julio20230806_R2IZLN6PKN.nwb

Found remote theta in trial  [63, 63]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230806_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:09:24,676][WARNING]: Skipped checksum for file with hash: ab46f97d-eaaf-9255-deea-c2d569407c36, and path: /stelmo/nwb/analysis/julio20230807/julio20230807_UXDGHP2JUV.nwb
WARNING:datajoint:Skipped checksum for file with hash: ab46f97d-eaaf-9255-deea-c2d569407c36, and path: /stelmo/nwb/analysis/julio20230807/julio20230807_UXDGHP2JUV.nwb

Found remote theta in trial  [19, 19]
Found remote theta in trial  [40, 40]
No triggered decode found for  {'nwb_file_name': 'julio20230806_.nwb', 'epoch': 10, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
julio20230807_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230807_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230807_ 4         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:09:35,821][WARNING]: Skipped checksum for file with hash: d97dde98-4e55-a244-6aef-a7b96cfc314f, and path: /stelmo/nwb/analysis/julio20230807/julio20230807_OWXTLVQPDS.nwb
WARNING:datajoint:Skipped checksum for file with hash: d97dde98-4e55-a244-6aef-a7b96cfc314f, and path: /stelmo/nwb/analysis/julio20230807/julio20230807_OWXTLVQPDS.nwb

Found remote theta in trial  [12]
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230807_ 6         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:09:46,830][WARNING]: Skipped checksum for file with hash: 56671ad1-6932-e770-135c-2d4cb8b0c9f2, and path: /stelmo/nwb/analysis/julio20230808/julio20230808_3HK2EZK6CM.nwb
WARNING:datajoint:Skipped checksum for file with hash: 56671ad1-6932-e770-135c-2d4cb8b0c9f2, and path: /stelmo/nwb/analysis/julio20230808/julio20230808_3HK2EZK6CM.nwb

No triggered decode found for  {'nwb_file_name': 'julio20230807_.nwb', 'epoch': 8, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
julio20230808_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230808_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:09:58,162][WARNING]: Skipped checksum for file with hash: b212dcc9-452e-756e-27a9-e2b161283eb9, and path: /stelmo/nwb/analysis/julio20230808/julio20230808_STIOP2RN2B.nwb
WARNING:datajoint:Skipped checksum for file with hash: b212dcc9-452e-756e-27a9-e2b161283eb9, and path: /stelmo/nwb/analysis/julio20230808/julio20230808_STIOP2RN2B.nwb

Found remote theta in trial  [41, 41, 41]
Found remote theta in trial  [67, 67, 67, 67, 67, 67, 67]
No triggered decode found for  {'nwb_file_name': 'julio20230808_.nwb', 'epoch': 4, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230808_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [9]

[2026-01-25 21:10:09,408][WARNING]: Skipped checksum for file with hash: 64aa5ceb-5e73-ce09-66e3-6e6005be5330, and path: /stelmo/nwb/analysis/julio20230808/julio20230808_8KNSAX4DX0.nwb
WARNING:datajoint:Skipped checksum for file with hash: 64aa5ceb-5e73-ce09-66e3-6e6005be5330, and path: /stelmo/nwb/analysis/julio20230808/julio20230808_8KNSAX4DX0.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230808_ 8         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:10:20,786][WARNING]: Skipped checksum for file with hash: 8c763658-3e9d-05df-78f0-1c5aaba8c88c, and path: /stelmo/nwb/analysis/julio20230809/julio20230809_X4Z8GCNV86.nwb
WARNING:datajoint:Skipped checksum for file with hash: 8c763658-3e9d-05df-78f0-1c5aaba8c88c, and path: /stelmo/nwb/analysis/julio20230809/julio20230809_X4Z8GCNV86.nwb

Found remote theta in trial  [27, 27, 27, 27, 27, 27, 27]
julio20230809_.nwb
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230809_ 2         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:10:31,376][WARNING]: Skipped checksum for file with hash: 5d88af3c-2fad-9a2f-98d7-5f5a7368b6e3, and path: /stelmo/nwb/analysis/julio20230809/julio20230809_MI783RTYOC.nwb
WARNING:datajoint:Skipped checksum for file with hash: 5d88af3c-2fad-9a2f-98d7-5f5a7368b6e3, and path: /stelmo/nwb/analysis/julio20230809/julio20230809_MI783RTYOC.nwb

Found remote theta in trial  [26, 26, 26, 26, 26, 26, 26, 26, 26, 26, 26]
No triggered decode found for  {'nwb_file_name': 'julio20230809_.nwb', 'epoch': 3, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230809_.nwb', 'epoch': 5, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230809_ 7         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [32]
Found remote theta in trial  [68, 68, 68]

[2026-01-25 21:10:42,544][WARNING]: Skipped checksum for file with hash: 9df8ba28-57f1-74a0-5c6b-08f79d541903, and path: /stelmo/nwb/analysis/julio20230809/julio20230809_R2UUI6MF7C.nwb
WARNING:datajoint:Skipped checksum for file with hash: 9df8ba28-57f1-74a0-5c6b-08f79d541903, and path: /stelmo/nwb/analysis/julio20230809/julio20230809_R2UUI6MF7C.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230809_ 9         0.1                                         =BLOB=
 (Total: 1)

[2026-01-25 21:10:53,587][WARNING]: Skipped checksum for file with hash: 0297a3de-2185-a95a-9190-69ee60adbe1a, and path: /stelmo/nwb/analysis/julio20230810/julio20230810_2STLURTWKM.nwb
WARNING:datajoint:Skipped checksum for file with hash: 0297a3de-2185-a95a-9190-69ee60adbe1a, and path: /stelmo/nwb/analysis/julio20230810/julio20230810_2STLURTWKM.nwb

julio20230810_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230810_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230810_ 4         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [31, 31]
Found remote theta in trial  [49]
Found remote theta in trial  [51, 51, 51, 51]

[2026-01-25 21:11:04,780][WARNING]: Skipped checksum for file with hash: 72f4211e-adf0-6c73-8d5a-afdf050eb28c, and path: /stelmo/nwb/analysis/julio20230810/julio20230810_SQ6CRIDB28.nwb
WARNING:datajoint:Skipped checksum for file with hash: 72f4211e-adf0-6c73-8d5a-afdf050eb28c, and path: /stelmo/nwb/analysis/julio20230810/julio20230810_SQ6CRIDB28.nwb

*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230810_ 6         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [12, 12, 12]

[2026-01-25 21:11:15,864][WARNING]: Skipped checksum for file with hash: f395c122-ded6-2d5d-9dc3-66f3411d5263, and path: /stelmo/nwb/analysis/julio20230811/julio20230811_HC4TIPN17N.nwb
WARNING:datajoint:Skipped checksum for file with hash: f395c122-ded6-2d5d-9dc3-66f3411d5263, and path: /stelmo/nwb/analysis/julio20230811/julio20230811_HC4TIPN17N.nwb

Found remote theta in trial  [68, 68]
No triggered decode found for  {'nwb_file_name': 'julio20230810_.nwb', 'epoch': 8, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
julio20230811_.nwb
No triggered decode found for  {'nwb_file_name': 'julio20230811_.nwb', 'epoch': 2, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230811_.nwb', 'epoch': 4, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230811_.nwb', 'epoch': 6, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
No triggered decode found for  {'nwb_file_name': 'julio20230811_.nwb', 'epoch': 7, 'proportion': 0.1, 'parameter': 'params_both_max_all_maze_2_state'}
*nwb_file_name *epoch    *proportion    analysis_file_ pandas_id     pandas
+------------+ +-------+ +------------+ +------------+ +-----------+ +--------+
julio20230811_ 9         0.1                                         =BLOB=
 (Total: 1)

Found remote theta in trial  [17, 17]

In [ ]:
success_animal

In [11]:
success_animal

{'lewis': 1, 'eliot': 1, 'molly': 1, 'klein': 1, 'julio': 1}

In [23]:
ChangeofMindRemoteTheta() & {"minimum_duration": 0.02}

*nwb_file_name *epoch    *proportion    *parameter     *minimum_durat pandas
+------------+ +-------+ +------------+ +------------+ +------------+ +--------+
eliot20221018_ 2         0.1            params_both_ma 0.02           =BLOB=
eliot20221018_ 5         0.1            params_both_ma 0.02           =BLOB=
eliot20221018_ 7         0.1            params_both_ma 0.02           =BLOB=
eliot20221018_ 9         0.1            params_both_ma 0.02           =BLOB=
eliot20221018_ 11        0.1            params_both_ma 0.02           =BLOB=
eliot20221019_ 2         0.1            params_both_ma 0.02           =BLOB=
eliot20221019_ 4         0.1            params_both_ma 0.02           =BLOB=
eliot20221019_ 6         0.1            params_both_ma 0.02           =BLOB=
eliot20221019_ 8         0.1            params_both_ma 0.02           =BLOB=
eliot20221019_ 10        0.1            params_both_ma 0.02           =BLOB=
eliot20221020_ 2         0.1            params_both_ma 0.02           =BLOB=
eliot20221020_ 4         0.1            params_both_ma 0.02           =BLOB=
   ...
 (Total: 164)